version: "3.8"
services:

  # Frontend
  frontend:
    image: mhib/tlcfrontend
    container_name: container_frontend
    hostname: frontend
    ports:
      - "1080:80" # HTTP
    depends_on:
     - api
     - etherpad
    restart: always # Redémarre le service si l'API n'est pas prête ou qu'elle redémarre
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

  # Backend
  api:
    image: mhib/tlcbackend
    container_name: container_api
    hostname: api
    depends_on:
        db:
          condition: service_healthy
    restart: on-failure # Redémarre le service si la base de données n'est pas prête

  db:
    image: mysql
    ports:
      - "3306:3306"
    container_name: container_db
    hostname: db
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=tlc
      - MYSQL_USER=tlc
      - MYSQL_PASSWORD=tlc
    healthcheck: # Attends que la base de données soit prête
      test: ["CMD", "mysqladmin", "ping", "-h", "db", "--user=$$MYSQL_USER", "--password=$$MYSQL_PASSWORD"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 30s
    volumes:
      - ./db:/var/lib/mysql # Stocke les données de la base de données

  etherpad:
    image: etherpad/etherpad
    container_name: container_etherpad
    ports:
      - "9001:9001"
    volumes:
      - ./APIKEY.txt:/opt/etherpad-lite/APIKEY.txt

  mail:
    image: bytemark/smtp
    container_name: container_mail
    restart: always
    ports:
      - "2525:25"