version: "3.8"
services:

  # Frontend
  frontend:
    image: mhib/tlcfrontend
    container_name: container_frontend
    hostname: frontend
    ports:
      - "1080:80" # HTTP
      - "443:443" # HTTPS
    depends_on:
        - api
        - etherpad

  # Backend
  api:
    image: mhib/tlcbackend
    container_name: container_api
    hostname: api
    depends_on:
        - db

  db:
    image: mysql
    ports:
      - "3306:3306"
    container_name: container_db
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=tlc
      - MYSQL_USER=tlc
      - MYSQL_PASSWORD=tlc

  etherpad:
    image: etherpad/etherpad
    container_name: container_etherpad
    ports:
      - "9001:9001"
    volumes:
      - ./APIKEY.txt:/opt/etherpad-lite/APIKEY.txt

  mail:
    image: bytemark/smtp
    container_name: container_mail
    restart: always
    ports:
      - "2525:25"